### ISSUE TITLE
Text display problems on Retina display Macintosh computers

### ISSUE THREAD

**Issue by charlesh88** [nasa/mct#275]
![screen shot 2014-03-17 at 3 47 34 pm](https://f.cloud.github.com/assets/1056412/2442659/2c71cb64-ae26-11e3-883b-8f605bda36c2.png)

When moving an object, the resulting Move / Copy / Copy Linked dialog box message reads "...Would you like tomove, copy or link...". 

There needs to be a space between "to" and "move".

**Comment by charlesh88** [comment]
Closing this issue for now as will not resolve; we can re-open later if this becomes a real issue for an existing client base.

**Comment by 1genius** [comment]
What java version are you using when you received this text problem.  I also have a mac retina and I’m using java version 8.  I didn’t download mct on my computer yet.  Could you send me a screen shot of the problem with the text?  I would appreciate.
